name: rogp

dependencies:
    - python=3.6
    - numpy
    - flake8
    - dill
    - IPython
    - jupyter
    - plotly
    - matplotlib
    - pytest
    - pytest-cov
    - pip:
        - GPy
        - pyDOE
        - pandas
        - sklearn
        - pyomo
        - coordinates
        - ipdb
        - setuptools

